### ISSUE TITLE
Error with latest Classic Era patch

### ISSUE THREAD

**Issue by dabadoo** [doadin/PlexusStatusEnemyTarget#1]
Getting this error with latest classic era patch. Unsure if it's taint related.

Happens when the targeting triggers.

`2x .../PlexusStatusEnemyTarget/PlexusStatusEnemyTarget.lua:296: attempt to index upvalue 'icon_map' (a nil value)
[string "@PlexusStatusEnemyTarget/PlexusStatusEnemyTarget.lua"]:296: in function `UpdateUnit'
[string "@PlexusStatusEnemyTarget/PlexusStatusEnemyTarget.lua"]:213: in function `?'
[string "@ActionbarPlus/Core/ExtLib/WowAce/Ace3/AceTimer-3.0-17/AceTimer-3.0.lua"]:55: in function <...ore/ExtLib/WowAce/Ace3/AceTimer-3.0/AceTimer-3.0.lua:50>

Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @ActionbarPlus/Core/ExtLib/WowAce/Ace3/AceAddon-3.0/AceAddon-3.0.lua:363
 Enable = <function> defined @ActionbarPlus/Core/ExtLib/WowAce/Ace3/AceAddon-3.0/AceAddon-3.0.lua:290
 NewModule = <function> defined @ActionbarPlus/Core/ExtLib/WowAce/Ace3/AceAddon-3.0/AceAddon-3.0.lua:231
 EnableModule = <function> defined @ActionbarPlus/Core/ExtLib/WowAce/Ace3/AceAddon-3.0/AceAddon-3.0.lua:328
 modules = <table> {
 }
 CancelTimer = <function> defined @ActionbarPlus/Core/ExtLib/WowAce/Ace3/AceTimer-3.0/AceTimer-3.0.lua:147
 IterateEmbeds = <function> defined @ActionbarPlus/Core/ExtLib/WowAce/Ace3/AceAddon-3.0/AceAddon-3.0.lua:438
 defaultModuleLibraries = <table> {
 }
 TimeLeft = <function> defined @ActionbarPlus/Core/ExtLib/WowAce/Ace3/AceTimer-3.0/AceTimer-3.0.lua:172
 ScheduleRepeatingTimer = <function> defined @ActionbarPlus/Core/ExtLib/WowAce/Ace3/AceTimer-3.0/AceTimer-3.0.lua:129
 CancelAllTimers = <function> defined @ActionbarPlus/Core/ExtLib/WowAce/Ace3/AceTimer-3.0/AceTimer-3.0.lua:160
 SetDefaultModulePrototype = <function> defined @ActionbarPlus/Core/ExtLib/WowAce/Ace3/AceAddon-3.0/AceAddon-3.0.lua:405
 timer = <table> {
 }
 options = <table> {
 }
 name = "Plexus_PlexusStatus_PlexusStatusEnemyTarget"
 IsEnabled = <function> defined @ActionbarPlus/Core/ExtLib/WowAce/Ace3/AceAddon-3.0/AceAddon-3.0.lua:447
 orderedModules = <table> {
 }
 ScheduleTimer = <function> defined @ActionbarPlus/Core/ExtLib/WowAce/Ace3/AceTimer-3.0/AceTimer-3.0.lua:94
 DisableModule = <function> defined @ActionbarPlus/Core/ExtLib/WowAce/Ace3/AceAddon-3.0/AceAddon-3.0.lua:346
 ResetVariables = <function> defined @PlexusStatusEnemyTarget/PlexusStatusEnemyTarget.lua:143
 defaultDB = <table> {
 }
 IsHostileNpcUnit = <function> defined @PlexusStatusEnemyTarget/PlexusStatusEnemyTarget.lua:100
 baseName = "PlexusStatusEnemyTarget"
 RegisterMessage = <function> defined @ActionbarPlus/Core/ExtLib/WowAce/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
 UnregisterMessage = <function> defined @ActionbarPlus/Core/ExtLib/WowAce/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:143
 UpdateUnit = <function> defined @PlexusStatusEnemyTarget/PlexusStatusEnemyTarget.lua:271
 OnUpdate = <function> defined @PlexusStatusEnemyTarget/PlexusStatusEnemyTarget.lua:194
 menuName = "Enemy incoming spell"
 super = <table> {
 }
 OnStatusEnable = <function> defined @PlexusStatusEnemyTarget/PlexusStatusEnemyTarget.lua:152
 IsModule = <function> defined @ActionbarPlus/Core/ExtLib/WowAce/Ace3/AceAddon-3.0/AceAddon-3.0.lua:213
 db = <table> {
 }
 SetDefaultModuleState = <function> defined @ActionbarPlus/Core/ExtLib/WowAce/Ace3/AceAddon-3.0/AceAddon-3.0.lua:383
 UnitCastStop = <function> defined @PlexusStatusEnemyTarget/PlexusStatusEnemyTarget.lua:139
 TryToStop = <function> defined @PlexusStatusEnemyTarget/PlexusStatusEnemyTarget.lua:129
 SetEnabledState = <function> defined @ActionbarPlus/Core/ExtLib/WowAce/Ace3/AceAddon-3.0/AceAddon-3.0.lua:420
 OnInitialize = <function> defined @PlexusStatusEnemyTarget/PlexusStatusEnemyTarget.lua:87
 enabledState = true
 COMBAT_LOG_EVENT_UNFILTERED = <function> defined @PlexusStatusEnemyTarget/PlexusStatusEnemyTarget.lua:107
 RegisterEvent = <function> defined @ActionbarPlus/Core/ExtLib/WowAce/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
 UnregisterAllMessages = <function> defined @ActionbarPlus/Core/ExtLib/WowAce/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:164
 OnStatusDisable = <function> defined @PlexusStatusEnemyTarget/PlexusStatusEnemyTarget.lua:169
 UnregisterAl`

**Comment by doadin** [comment]
I just pushed an update out v1.2.2 it may take a min to get through curseforge/updaters or you can get it here on github in releases. Let me know if you still have issues after this update, thanks!

**Comment by dabadoo** [comment]
From just a quick test: No error and think everything is working well.

Thanks! <3
